-- DropForeignKey
ALTER TABLE "APPLICATION" DROP CONSTRAINT "APPLICATION_CV_id_fkey";

-- DropForeignKey
ALTER TABLE "CV" DROP CONSTRAINT "CV_cadidate_id_fkey";

-- AddForeignKey
ALTER TABLE "CV" ADD CONSTRAINT "CV_cadidate_id_fkey" FOREIGN KEY ("cadidate_id") REFERENCES "CANDIDATE"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "APPLICATION" ADD CONSTRAINT "APPLICATION_CV_id_fkey" FOREIGN KEY ("CV_id") REFERENCES "CV"("id") ON DELETE CASCADE ON UPDATE CASCADE;
